apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonesoup-spring-boot-zlnq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonesoup-spring-boot-zlnq
    app.kubernetes.io/part-of: my-app
  name: stonesoup-spring-boot-zlnq
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: stonesoup-spring-boot-zlnq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: stonesoup-spring-boot-zlnq
    spec:
      containers:
      - image: quay.io/ch007m/stonesoup:NA_QT-stonesoup-spring-boot-zlnq
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
